CREATE DATABASE Optus;

USE Optus;


CREATE TABLE Usuario(
IdUsuarios INT PRIMARY KEY IDENTITY NOT NULL,
Nome VARCHAR(100) NOT NULL,
Permissao BINARY NOT NULL,
Senha VARCHAR (8) NOT NULL,
Email VARCHAR (50) NOT NULL
);

CREATE TABLE Estilo(
IdEstilo INT PRIMARY KEY IDENTITY NOT NULL,
Nome VARCHAR (100) NOT NULL
);

CREATE TABLE Artista(
IdArtista INT PRIMARY KEY IDENTITY NOT NULL,
Nome VARCHAR (100) NOT NULL,

IdEstilo INT FOREIGN KEY REFERENCES Estilo (IdEstilo)
);

CREATE TABLE Album(
IdAlbum INT PRIMARY KEY IDENTITY NOT NULL,
Nome VARCHAR (100) NOT NULL,
DataNascimento DATE NOT NULL,
QtdMinutos DATETIME NOT NULL,
Ativo BINARY NOT NULL,

IdArtista INT FOREIGN KEY REFERENCES Artista (IdArtista)
);


CREATE TABLE EstiloAlbum(
IdEstiloAlbum INT PRIMARY KEY IDENTITY NOT NULL,

IdEstilo INT FOREIGN KEY REFERENCES Estilo (IdEstilo),
IdAlbum INT FOREIGN KEY REFERENCES Album (IdAlbum)

);