CREATE DATABASE PetShop;

USE PetShop;

CREATE TABLE Clinicas(
IdClinicas INT PRIMARY KEY IDENTITY NOT NULL,
Nome VARCHAR(100) NOT NULL,
Endereco VARCHAR (400) NOT NULL
);

CREATE TABLE Donos (
IdDonos INT PRIMARY KEY IDENTITY NOT NULL,
Nome VARCHAR(100) NOT NULL
);

CREATE TABLE TipoDePet (
IdTipoDePet INT PRIMARY KEY IDENTITY NOT NULL,
Descricao VARCHAR(100) NOT NULL
);

CREATE TABLE Veterinario(
IdVet INT PRIMARY KEY IDENTITY NOT NULL,
CRMV VARCHAR(50) NOT NULL,
Nome VARCHAR(100) NOT NULL,

IdClinicas INT FOREIGN KEY REFERENCES Clinicas(IdClinicas)
);

CREATE TABLE Raca(
IdRaca INT PRIMARY KEY IDENTITY NOT NULL,
Descricao VARCHAR(500) NOT NULL,


IdTipoDePet INT FOREIGN KEY REFERENCES TipoDePet(IdTipoDePet)
);

CREATE TABLE Pets(
IdPets INT PRIMARY KEY IDENTITY NOT NULL,
Nome VARCHAR(100) NOT NULL,
DataNascimento DATETIME NOT NULL,

IdRaca INT FOREIGN KEY REFERENCES Raca(IdRaca),
IdDonos INT FOREIGN KEY REFERENCES Donos(IdDonos)
);

CREATE TABLE Atendimentos(
IdAtendimentos INT PRIMARY KEY IDENTITY NOT NULL,
Descricao VARCHAR(500) NOT NULL,
DataAtendimento DATETIME NOT NULL,

IdPets INT FOREIGN KEY REFERENCES Pets(IdPets),
IdVet INT FOREIGN KEY REFERENCES Veterinario(IdVet)
);